### ISSUE TITLE
Remove clap as a dependency in Cargo.toml

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [chipsenkbeil/service-manager-rs#16]
I am wondering if it is possible to remove clap as a dependency of the main build in Cargo.toml (or at least make it a dev dependency).

I see it used also in system-tests/Cargo.toml and wonder if that would be sufficient?

**Comment by chipsenkbeil** [comment]
It's an optional dependency. Is there a reason you need it fully removed? By default, if you don't enable the dependency through the clap feature, it shouldn't be compiled at all.

 For context, it's supported to compile parts of this library for use as arguments in clap, which https://github.com/chipsenkbeil/distant uses.

**Comment by andrewdavidmackenzie** [comment]
Sorry, I didn't notice it was optional! :-( 
I am building on a very small device and was trying to reduce build time/memory - just FYI
