### ISSUE TITLE
Some ideas seek the author's opinion.

### ISSUE THREAD

**Issue by hvvvvvvv** [chipsenkbeil/service-manager-rs#29]
I plan to submit some potentially breaking updates in my PRs, such as adding fields in ServiceInstallCtx and adding values to the TypedServiceManager enumeration. I noticed that a PR to add methods in ServiceManager has already been merged in the repository, which is already a breaking change. Would the author mind merging the PRs I described?

**Comment by chipsenkbeil** [comment]
Sure, feel free to submit PRs and I'll review them.

I'm traveling for the next couple of weeks, so the PRs may not get merged immediately.
