### ISSUE TITLE
Compile error in Android Termux.

### ISSUE THREAD

**Issue by mokeyish** [chipsenkbeil/service-manager-rs#4]
https://github.com/chipsenkbeil/service-manager-rs/blob/59736e1b0b8c7c2af05441145575e5c459eb4542/src/kind.rs#L26

```error
error[E0599]: no variant or associated item named native found for enum kind::ServiceManagerKind in the current scope
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/service-manager-0.2.0/src/typed.rs:89:45
   |
89 |         Ok(Self::target(ServiceManagerKind::native()?))
   |                                             ^^^^^^ variant or associated item not found in kind::ServiceManagerKind
```

**Comment by chipsenkbeil** [comment]
What service manager would Android Termux use? I'm not familiar with that platform, and it isn't supported via this crate at the moment. At the moment, these systems are supported:

* Windows
* MacOS
* Linux
* FreeBSD
* DragonflyBSD
* OpenBSD
* NetBSD

I can add a default, native implementation for Android, but I wouldn't know what it would use.

**Comment by mokeyish** [comment]
I'm planning to use `service-manager` to manager service for my software https://github.com/mokeyish/smartdns-rs.
It planned to support Android Termux.

Fix it first  to avoid compilation errors?

**Comment by chipsenkbeil** [comment]
@mokeyish so what service manager does Android Termux use? Systemd?

**Comment by chipsenkbeil** [comment]
It looks like Android Termux uses `runit` as the service manager, which isn't currently supported by this library. See #1 for the request to add support for `sv`, which Android Termux also uses as [described here](https://wiki.termux.com/wiki/Termux-services) and in [this blog post](https://mrinjamul.medium.com/create-and-manage-services-in-termux-linux-based-android-terminal-5120c4694199).

**Comment by mokeyish** [comment]
Yes, it use `runit`.  I used `sv` a long time ago, but currently, I forgot how to use it .

**Comment by mokeyish** [comment]
@chipsenkbeil  BTW, Can `qualifier` and `organization` be optional? I want to use `smartdns-rs` as service label directly.

https://github.com/chipsenkbeil/service-manager-rs/blob/f738b98e5e44034c897f0a277a0cabff8ff8b6f8/src/lib.rs#L95-L103

**Comment by chipsenkbeil** [comment]
> @chipsenkbeil BTW, Can `qualifier` and `organization` be optional? I want to use `smartdns-rs` as service label directly.
> 
> https://github.com/chipsenkbeil/service-manager-rs/blob/f738b98e5e44034c897f0a277a0cabff8ff8b6f8/src/lib.rs#L95-L103

Depending on the service manager, they may or may not be optional. Which service manager are you using? You can always put in an empty string or placeholder for them, but they may behave a little strangely.

**Comment by chipsenkbeil** [comment]
No longer fails to compile thanks to #9.
