### ISSUE TITLE
Feature request: Print the status of service?

### ISSUE THREAD

**Issue by mokeyish** [chipsenkbeil/service-manager-rs#5]
https://github.com/chipsenkbeil/service-manager-rs/blob/f738b98e5e44034c897f0a277a0cabff8ff8b6f8/src/lib.rs#L26

**Comment by chipsenkbeil** [comment]
I'm open to a PR here if you want to propose a way to do this! My expectation is that there would be a method to return an enum that represents a generic status for the service manager. Maybe something like

```rust
enum ServiceStatus {
    Running,
    Dead,
}
```

A user of this library could then write their own print method for the status itself.
