### ISSUE TITLE
Feature request: Allow custom service file template?

### ISSUE THREAD

**Issue by mokeyish** [chipsenkbeil/service-manager-rs#6]
Currently, [service-manager-rs](https://github.com/chipsenkbeil/service-manager-rs) has default service template, but custom templates are not support.

https://github.com/chipsenkbeil/service-manager-rs/blob/f738b98e5e44034c897f0a277a0cabff8ff8b6f8/src/openrc.rs#L169

https://github.com/chipsenkbeil/service-manager-rs/blob/f738b98e5e44034c897f0a277a0cabff8ff8b6f8/src/launchd.rs#L188

---

Gitea has provide different service templates for various operating system: https://github.com/go-gitea/gitea/tree/main/contrib/init

**Comment by chipsenkbeil** [comment]
I'm open to a PR here if you want to propose a way to do this!

**Comment by dsully** [comment]
A very basic version would be allowing a `Option<String>` (or `bytes`) to be passed in to `fn install`, and to not run the respective `make_` function if `Some()`.

Would that work for you @chipsenkbeil ?

**Comment by chipsenkbeil** [comment]
Seems fine to me :)
